import { createHash, randomUUID } from "node:crypto";
import { z } from "zod";
import type { MediaLibraryAsset } from "@/lib/media-library";
import { DEFAULT_STORE_THEME_DENSITY_SCALE, DEFAULT_STORE_THEME_RADIUS_SCALE } from "@/lib/cms/store-theme-contract";

export const MAX_RESTORE_JSON_BYTES = 3 * 1024 * 1024;
export const MAX_RESTORE_ROWS = 5_000;
export const MAX_RESTORE_MEDIA_FILES = 200;
export const MAX_RESTORE_MEDIA_BYTES = 250 * 1024 * 1024;
export const MAX_RESTORE_IMAGE_BYTES = 10 * 1024 * 1024;
export const MAX_RESTORE_VIDEO_BYTES = 50 * 1024 * 1024;

export const RESTORE_TABLE_KEYS = [
  "store_business_profiles", "store_themes", "store_pages", "store_page_blocks", "store_page_revisions",
  "blog_posts", "products", "product_categories", "product_types", "coupon_codes", "site_settings",
  "store_memberships", "store_staff_invites", "orders", "product_reviews", "contact_messages",
  "customer_addresses", "store_customer_profiles", "store_analytics_events", "store_subscriptions",
] as const;

const RESTORE_DATA_KEYS = new Set<string>(["store", ...RESTORE_TABLE_KEYS]);
const UUID_SCHEMA = z.string().uuid();

export const restoreOptionsSchema = z.object({
  targetStoreId: z.string().uuid(),
  replaceTargetContent: z.boolean().default(true),
  preserveTargetSlug: z.boolean().default(true),
  preserveTargetDomain: z.boolean().default(true),
  keepImportedStoreDraft: z.boolean().default(true),
  includeOperationalData: z.boolean().default(false),
  accessImportMode: z.enum(["none", "invites_only", "memberships_and_invites"]).default("none"),
  replaceSubscription: z.boolean().default(false),
  format: z.enum(["json", "zip"]),
});
export type StoreRestoreOptions = z.infer<typeof restoreOptionsSchema>;

export const restoreMediaDescriptorSchema = z.object({
  originalUrl: z.string().url(), fileName: z.string().min(1).max(160), mimeType: z.string().max(160).optional(),
  resourceType: z.enum(["image", "video"]).default("image"), folder: z.string().max(240).default("imports"),
  declaredBytes: z.number().int().positive().max(MAX_RESTORE_VIDEO_BYTES),
});
export const restoreManifestSchema = z.object({
  version: z.enum(["2026-07-02", "2026-07-26"]), exportedAt: z.string().min(1).max(80),
  source: z.object({ storeId: z.string().min(1).max(200), storeSlug: z.string().max(200), storeName: z.string().min(1).max(300) }),
  metadata: z.object({ includedOperationalData: z.boolean().optional(), includedAccessData: z.boolean().optional(), includedMediaFiles: z.boolean().optional(), tableKeys: z.array(z.string().max(100)).max(100).optional() }).optional(),
  data: z.record(z.string(), z.unknown()), mediaFiles: z.array(restoreMediaDescriptorSchema).max(MAX_RESTORE_MEDIA_FILES).default([]),
});
export type StoreRestoreManifest = z.infer<typeof restoreManifestSchema>;
export type RestoreAccessMode = StoreRestoreOptions["accessImportMode"];
export type StoreRestoreTarget = { id: string; owner_id: string | null; name: string; slug: string; custom_domain: string | null; description: string | null; currency_code: string | null; locale: string | null; plan: string | null; store_type: string | null; logo_url: string | null; is_published: boolean | null };
export type RestoreStagedMedia = { originalUrl: string; path: string; declaredBytes: number; asset: MediaLibraryAsset };
export type RestoreNormalizationContext = {
  operationId: string; actorId: string; actorExistingRole: "owner" | "admin" | "editor" | "viewer" | null;
  target: StoreRestoreTarget; authUserIds: Set<string>; validThemePackageIds: Set<string>;
  existingSubscription: { id?: string | null; provider?: string | null; provider_subscription_id?: string | null } | null;
  targetHasHomepage?: boolean; stagedMedia?: RestoreStagedMedia[]; now?: string; makeId?: () => string;
};

function record(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object.`); return value as Record<string, unknown>; }
function rows(data: Record<string, unknown>, key: string) { const value = data[key]; if (value === undefined) return [] as Record<string, unknown>[]; if (!Array.isArray(value)) throw new Error(`${key} must be an array.`); return value.map((item, index) => record(item, `${key}[${index}]`)); }
function text(value: unknown, fallback = "") { return typeof value === "string" ? value : fallback; }
function nullableText(value: unknown) { return typeof value === "string" && value.length > 0 ? value : null; }
function requiredText(value: unknown, label: string) { const next = text(value).trim(); if (!next) throw new Error(`${label} is required.`); return next; }
function bool(value: unknown, fallback = false) { return typeof value === "boolean" ? value : fallback; }
function int(value: unknown, fallback = 0) { const number = typeof value === "number" ? value : Number(value); return Number.isFinite(number) ? Math.trunc(number) : fallback; }
function numberValue(value: unknown, fallback = 0) { const number = typeof value === "number" ? value : Number(value); return Number.isFinite(number) ? number : fallback; }
function stringArray(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function jsonValue(value: unknown, fallback: unknown = {}) { return value === undefined || value === null ? fallback : value; }
function sourceUuid(row: Record<string, unknown>, key: string, label: string) { const parsed = UUID_SCHEMA.safeParse(row[key]); if (!parsed.success) throw new Error(`${label}.${key} must be a UUID.`); return parsed.data; }
function optionalUuid(value: unknown, label: string) { if (value === null || value === undefined || value === "") return null; const parsed = UUID_SCHEMA.safeParse(value); if (!parsed.success) throw new Error(`${label} must be a UUID.`); return parsed.data; }
function requireMapped(map: Map<string, string>, sourceId: unknown, label: string) { const parsed = UUID_SCHEMA.safeParse(sourceId); if (!parsed.success) throw new Error(`${label} must be a UUID.`); const mapped = map.get(parsed.data); if (!mapped) throw new Error(`${label} references a row that is not included in the backup.`); return mapped; }

export function validateRestoreManifest(input: unknown) {
  const manifest = restoreManifestSchema.parse(input);
  for (const key of Object.keys(manifest.data)) if (!RESTORE_DATA_KEYS.has(key)) throw new Error(`Unsupported backup table: ${key}`);
  if (!manifest.data.store) throw new Error("Backup is missing the store row."); record(manifest.data.store, "store");
  for (const key of RESTORE_TABLE_KEYS) rows(manifest.data, key);
  const rowCount = countRestoreRows(manifest); if (rowCount > MAX_RESTORE_ROWS) throw new Error(`Backup contains ${rowCount} database rows; the synchronous restore limit is ${MAX_RESTORE_ROWS}.`);
  const aggregateMediaBytes = manifest.mediaFiles.reduce((sum, file) => { const max = file.resourceType === "video" ? MAX_RESTORE_VIDEO_BYTES : MAX_RESTORE_IMAGE_BYTES; if (file.declaredBytes > max) throw new Error(`${file.fileName} exceeds the ${file.resourceType === "video" ? "50 MiB" : "10 MiB"} restore limit.`); return sum + file.declaredBytes; }, 0);
  if (aggregateMediaBytes > MAX_RESTORE_MEDIA_BYTES) throw new Error("Packaged restore media exceeds the 250 MiB aggregate limit.");
  validateRequiredReferences(manifest.data); return manifest;
}
export function countRestoreRows(manifest: StoreRestoreManifest) { return RESTORE_TABLE_KEYS.reduce((sum, key) => sum + (Array.isArray(manifest.data[key]) ? (manifest.data[key] as unknown[]).length : 0), 0); }

export function validateRequiredReferences(data: Record<string, unknown>) {
  const productRows=rows(data,"products"), orderRows=rows(data,"orders"), categoryRows=rows(data,"product_categories"), pageRows=rows(data,"store_pages");
  const productIds=new Set(productRows.map((row,i)=>sourceUuid(row,"id",`products[${i}]`))), orderIds=new Set(orderRows.map((row,i)=>sourceUuid(row,"id",`orders[${i}]`))), categoryIds=new Set(categoryRows.map((row,i)=>sourceUuid(row,"id",`product_categories[${i}]`))), pageIds=new Set(pageRows.map((row,i)=>sourceUuid(row,"id",`store_pages[${i}]`)));
  const pageSlugs=new Set<string>(); let homepages=0; pageRows.forEach((row,index)=>{ const slug=requiredText(row.slug,`store_pages[${index}].slug`); if(pageSlugs.has(slug)) throw new Error(`Duplicate page slug in backup: ${slug}`); pageSlugs.add(slug); if(row.is_homepage===true) homepages+=1; }); if(homepages>1) throw new Error("Backup contains more than one homepage.");
  const blogSlugs=new Set<string>(); rows(data,"blog_posts").forEach((row,index)=>{ const slug=requiredText(row.slug,`blog_posts[${index}].slug`); if(blogSlugs.has(slug)) throw new Error(`Duplicate blog slug in backup: ${slug}`); blogSlugs.add(slug); for(const id of Array.isArray(row.embedded_product_ids)?row.embedded_product_ids:[]){ if(typeof id!=="string"||!productIds.has(id)) throw new Error(`blog_posts[${index}].embedded_product_ids references a product not included in the backup.`); } });
  categoryRows.forEach((row,index)=>{ if(row.parent_id!==null&&row.parent_id!==undefined&&row.parent_id!==""){ const parent=optionalUuid(row.parent_id,`product_categories[${index}].parent_id`); if(!parent||!categoryIds.has(parent)) throw new Error(`product_categories[${index}].parent_id references a category not included in the backup.`); } });
  rows(data,"store_page_blocks").forEach((row,index)=>{ const pageId=optionalUuid(row.page_id,`store_page_blocks[${index}].page_id`); if(!pageId||!pageIds.has(pageId)) throw new Error(`store_page_blocks[${index}].page_id references a page not included in the backup.`); });
  rows(data,"store_page_revisions").forEach((row,index)=>{ const pageId=optionalUuid(row.page_id,`store_page_revisions[${index}].page_id`); if(!pageId||!pageIds.has(pageId)) throw new Error(`store_page_revisions[${index}].page_id references a page not included in the backup.`); });
  rows(data,"product_reviews").forEach((row,index)=>{ const productId=optionalUuid(row.product_id,`product_reviews[${index}].product_id`); if(!productId||!productIds.has(productId)) throw new Error(`product_reviews[${index}].product_id references a product not included in the backup.`); if(row.order_id!==null&&row.order_id!==undefined&&row.order_id!==""){ const orderId=optionalUuid(row.order_id,`product_reviews[${index}].order_id`); if(!orderId||!orderIds.has(orderId)) throw new Error(`product_reviews[${index}].order_id references an order not included in the backup.`); } });
}

export async function readBoundedRestoreJson(req: Request) { const lengthHeader=req.headers.get("content-length"); if(lengthHeader&&Number(lengthHeader)>MAX_RESTORE_JSON_BYTES) throw new RestoreHttpError(413,"Restore request exceeds the 3 MiB JSON limit."); const bytes=new Uint8Array(await req.arrayBuffer()); if(bytes.byteLength>MAX_RESTORE_JSON_BYTES) throw new RestoreHttpError(413,"Restore request exceeds the 3 MiB JSON limit."); try{return JSON.parse(new TextDecoder().decode(bytes)) as unknown;}catch{throw new RestoreHttpError(400,"Restore request is not valid JSON.");} }
export class RestoreHttpError extends Error { constructor(public status:number,message:string){super(message);} }
function canonicalize(value:unknown):unknown{ if(Array.isArray(value))return value.map(canonicalize); if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value as Record<string,unknown>).sort().map(key=>[key,canonicalize((value as Record<string,unknown>)[key])])); return value; }
export function digestRestoreRequest(manifest:StoreRestoreManifest,options:StoreRestoreOptions){ return createHash("sha256").update(JSON.stringify(canonicalize({manifest,options}))).digest("hex"); }
function replaceMappedIds<T>(value:T,maps:Array<Map<string,string>>):T{ if(typeof value==="string"){for(const map of maps){const replacement=map.get(value);if(replacement)return replacement as T;}return value;} if(Array.isArray(value))return value.map(item=>replaceMappedIds(item,maps)) as T; if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,replaceMappedIds(item,maps)])) as T; return value; }
function replaceUrls<T>(value:T,mediaByUrl:Map<string,RestoreStagedMedia>):T{ if(typeof value==="string")return(mediaByUrl.get(value)?.asset.url??value)as T; if(Array.isArray(value))return value.map(item=>replaceUrls(item,mediaByUrl))as T; if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,replaceUrls(item,mediaByUrl)]))as T; return value; }
function rewriteSettingValue(key:string,value:unknown,mediaByUrl:Map<string,RestoreStagedMedia>,maps:Array<Map<string,string>>){ if(key==="media_library"&&Array.isArray(value))return value.map(entry=>{if(!entry||typeof entry!=="object")return entry;const staged=mediaByUrl.get(text((entry as Record<string,unknown>).url));return staged?staged.asset:replaceMappedIds(replaceUrls(entry,mediaByUrl),maps);}); return replaceMappedIds(replaceUrls(value,mediaByUrl),maps); }
function makeMap(sourceRows:Record<string,unknown>[],label:string,makeId:()=>string){const map=new Map<string,string>();sourceRows.forEach((row,index)=>map.set(sourceUuid(row,"id",`${label}[${index}]`),makeId()));return map;}
function roleValue(value:unknown):"owner"|"admin"|"editor"|"viewer"{return value==="owner"||value==="admin"||value==="editor"||value==="viewer"?value:"viewer";}
const ROLE_RANK={viewer:0,editor:1,admin:2,owner:3}as const; function atLeastRole(incoming:"owner"|"admin"|"editor"|"viewer",floor:"owner"|"admin"|"editor"|"viewer"|null){if(!floor)return incoming;return ROLE_RANK[incoming]>=ROLE_RANK[floor]?incoming:floor;}

export function normalizeStoreRestorePlan(manifest:StoreRestoreManifest,options:StoreRestoreOptions,context:RestoreNormalizationContext){
  validateRestoreManifest(manifest); const now=context.now??new Date().toISOString(), makeId=context.makeId??randomUUID, data=manifest.data, sourceStore=record(data.store,"store"), mediaByUrl=new Map((context.stagedMedia??[]).map(item=>[item.originalUrl,item]));
  const categoryRows=rows(data,"product_categories"),typeRows=rows(data,"product_types"),productRows=rows(data,"products"),pageRows=rows(data,"store_pages"),orderRows=rows(data,"orders");
  const categoryMap=makeMap(categoryRows,"product_categories",makeId),typeMap=makeMap(typeRows,"product_types",makeId),productMap=makeMap(productRows,"products",makeId),pageMap=makeMap(pageRows,"store_pages",makeId),orderMap=makeMap(orderRows,"orders",makeId),sharedMaps=[categoryMap,typeMap,productMap,pageMap,orderMap];
  const orderNumberMap=new Map<string,string>(),operationToken=context.operationId.replaceAll("-","").slice(0,12).toUpperCase(); orderRows.forEach((row,index)=>orderNumberMap.set(requiredText(row.order_number,`orders[${index}].order_number`),`IMP-${operationToken}-${String(index+1).padStart(4,"0")}`));
  const store_business_profiles=rows(data,"store_business_profiles").slice(0,1).map(row=>({store_id:context.target.id,business_family:text(row.business_family,"commerce"),catalog_mode:text(row.catalog_mode,"multi_product"),enabled_modules:jsonValue(row.enabled_modules,[]),created_at:now,updated_at:now,template_id:nullableText(row.template_id)}));
  const store_themes=rows(data,"store_themes").slice(0,1).map(row=>{const requestedPackage=optionalUuid(row.theme_package_id,"store_themes.theme_package_id");return{id:makeId(),store_id:context.target.id,preset_id:text(row.preset_id,"default"),mode:row.mode==="light"?"light":"dark",colors:replaceMappedIds(replaceUrls(jsonValue(row.colors,{}),mediaByUrl),sharedMaps),typography:jsonValue(row.typography,{}),components:replaceMappedIds(replaceUrls(jsonValue(row.components,{}),mediaByUrl),sharedMaps),custom_css:nullableText(row.custom_css),created_at:now,updated_at:now,theme_package_id:requestedPackage&&context.validThemePackageIds.has(requestedPackage)?requestedPackage:null,theme_package_version:row.theme_package_version==null?null:int(row.theme_package_version),overrides:replaceMappedIds(replaceUrls(jsonValue(row.overrides,{}),mediaByUrl),sharedMaps),resolved_tokens:jsonValue(row.resolved_tokens,{}),aesthetic:text(row.aesthetic,"minimal"),radius_scale:numberValue(row.radius_scale,DEFAULT_STORE_THEME_RADIUS_SCALE),density_scale:numberValue(row.density_scale,DEFAULT_STORE_THEME_DENSITY_SCALE),effects:jsonValue(row.effects,{parallax:false,intensity:"medium",hoverEffects:true,scrollReveals:false}),palette_source:nullableText(row.palette_source),palette_seed:nullableText(row.palette_seed),schema_version:int(row.schema_version,1)};});
  const product_categories=categoryRows.map((row,index)=>({id:categoryMap.get(sourceUuid(row,"id",`product_categories[${index}]`))!,name:requiredText(row.name,`product_categories[${index}].name`),parent_id:row.parent_id?requireMapped(categoryMap,row.parent_id,`product_categories[${index}].parent_id`):null,sort_order:int(row.sort_order),created_at:now,store_id:context.target.id}));
  const product_types=typeRows.map((row,index)=>({id:typeMap.get(sourceUuid(row,"id",`product_types[${index}]`))!,name:requiredText(row.name,`product_types[${index}].name`),sort_order:int(row.sort_order),created_at:now,store_id:context.target.id,metric_schema:replaceMappedIds(jsonValue(row.metric_schema,[]),sharedMaps)}));
  const products=productRows.map((row,index)=>({id:productMap.get(sourceUuid(row,"id",`products[${index}]`))!,name:requiredText(row.name,`products[${index}].name`),price:int(row.price),original_price:row.original_price==null?null:int(row.original_price),image_url:text(replaceUrls(text(row.image_url),mediaByUrl)),description:text(row.description),sizes:stringArray(row.sizes),colors:stringArray(row.colors),category:text(row.category,"Essentials"),type:text(row.type,"T-Shirt"),featured:bool(row.featured),badge:nullableText(row.badge),stock:int(row.stock),is_available:bool(row.is_available,true),created_at:now,updated_at:now,images:replaceUrls(stringArray(row.images),mediaByUrl),store_id:context.target.id,metric_values:replaceMappedIds(jsonValue(row.metric_values,{}),sharedMaps)}));
  const coupon_codes=rows(data,"coupon_codes").map((row,index)=>({id:makeId(),code:`RESTORE-${operationToken}-${String(index+1).padStart(4,"0")}`,discount_type:row.discount_type==="fixed"?"fixed":"percentage",discount_value:int(row.discount_value),min_order:int(row.min_order),max_uses:row.max_uses==null?null:int(row.max_uses),uses_count:int(row.uses_count),expires_at:nullableText(row.expires_at),is_active:bool(row.is_active,true),created_at:now,updated_at:now,store_id:context.target.id}));
  const blog_posts=rows(data,"blog_posts").map((row,index)=>({id:makeId(),store_id:context.target.id,title:requiredText(row.title,`blog_posts[${index}].title`),slug:requiredText(row.slug,`blog_posts[${index}].slug`),excerpt:nullableText(row.excerpt),content:text(row.content),featured_image:nullableText(replaceUrls(row.featured_image,mediaByUrl)),status:row.status==="published"?"published":"draft",seo_title:nullableText(row.seo_title),seo_description:nullableText(row.seo_description),published_at:nullableText(row.published_at),created_at:now,updated_at:now,category:nullableText(row.category),tags:stringArray(row.tags),author_name:nullableText(row.author_name),featured_image_alt:nullableText(row.featured_image_alt),is_featured:bool(row.is_featured),embedded_product_ids:(Array.isArray(row.embedded_product_ids)?row.embedded_product_ids:[]).map(id=>requireMapped(productMap,id,`blog_posts[${index}].embedded_product_ids`)),product_embed_title:nullableText(row.product_embed_title),product_embed_position:["before-content","after-intro","after-content"].includes(text(row.product_embed_position))?text(row.product_embed_position):"after-content",canonical_url:nullableText(row.canonical_url),og_image:nullableText(replaceUrls(row.og_image,mediaByUrl)),seo_keywords:stringArray(row.seo_keywords),noindex:bool(row.noindex)}));
  const ordersPlan=options.includeOperationalData?orderRows.map((row,index)=>{const sourceOrderNumber=requiredText(row.order_number,`orders[${index}].order_number`),sourceUser=optionalUuid(row.user_id,`orders[${index}].user_id`);return{id:orderMap.get(sourceUuid(row,"id",`orders[${index}]`))!,user_id:sourceUser&&context.authUserIds.has(sourceUser)?sourceUser:null,order_number:orderNumberMap.get(sourceOrderNumber)!,status:text(row.status,"pending"),items:replaceMappedIds(replaceUrls(jsonValue(row.items,[]),mediaByUrl),sharedMaps),subtotal:int(row.subtotal),delivery_fee:int(row.delivery_fee),total:int(row.total),customer_name:requiredText(row.customer_name,`orders[${index}].customer_name`),customer_phone:requiredText(row.customer_phone,`orders[${index}].customer_phone`),customer_email:nullableText(row.customer_email),shipping_address:requiredText(row.shipping_address,`orders[${index}].shipping_address`),shipping_city:requiredText(row.shipping_city,`orders[${index}].shipping_city`),payment_method:text(row.payment_method,"cod"),notes:nullableText(row.notes),created_at:nullableText(row.created_at)??now,updated_at:now,store_id:context.target.id,client_request_id:null};}):[];
  const product_reviews=options.includeOperationalData?rows(data,"product_reviews").map((row,index)=>({id:makeId(),product_id:requireMapped(productMap,row.product_id,`product_reviews[${index}].product_id`),user_id:sourceUuid(row,"user_id",`product_reviews[${index}]`),order_id:row.order_id?requireMapped(orderMap,row.order_id,`product_reviews[${index}].order_id`):null,author_name:requiredText(row.author_name,`product_reviews[${index}].author_name`).slice(0,100),rating:int(row.rating),review_text:nullableText(row.review_text)?.slice(0,500)??null,size_purchased:nullableText(row.size_purchased),status:["pending","approved","rejected"].includes(text(row.status))?text(row.status):"pending",admin_reply:nullableText(row.admin_reply),created_at:nullableText(row.created_at)??now,updated_at:now,image_url:nullableText(replaceUrls(row.image_url,mediaByUrl)),store_id:context.target.id})):[];
  const contact_messages=options.includeOperationalData?rows(data,"contact_messages").map((row,index)=>({id:makeId(),name:requiredText(row.name,`contact_messages[${index}].name`),email:requiredText(row.email,`contact_messages[${index}].email`),message:requiredText(row.message,`contact_messages[${index}].message`),is_read:bool(row.is_read),created_at:nullableText(row.created_at)??now,store_id:context.target.id})):[];
  const customer_addresses=options.includeOperationalData?rows(data,"customer_addresses").map((row,index)=>{const userId=sourceUuid(row,"user_id",`customer_addresses[${index}]`);if(!context.authUserIds.has(userId))throw new Error(`customer_addresses[${index}].user_id does not exist on the destination platform.`);return{id:makeId(),user_id:userId,label:text(row.label,"Home"),name:requiredText(row.name,`customer_addresses[${index}].name`),phone:requiredText(row.phone,`customer_addresses[${index}].phone`),address:requiredText(row.address,`customer_addresses[${index}].address`),city:requiredText(row.city,`customer_addresses[${index}].city`),is_default:bool(row.is_default),created_at:nullableText(row.created_at)??now,store_id:context.target.id};}):[];
  const store_customer_profiles=options.includeOperationalData?rows(data,"store_customer_profiles").map((row,index)=>{const userId=sourceUuid(row,"user_id",`store_customer_profiles[${index}]`);if(!context.authUserIds.has(userId))throw new Error(`store_customer_profiles[${index}].user_id does not exist on the destination platform.`);return{id:makeId(),store_id:context.target.id,user_id:userId,display_name:nullableText(row.display_name),avatar_url:nullableText(replaceUrls(row.avatar_url,mediaByUrl)),phone:nullableText(row.phone),email:nullableText(row.email),status:text(row.status,"active"),marketing_opt_in:bool(row.marketing_opt_in),notes:nullableText(row.notes),tags:stringArray(row.tags),created_at:now,updated_at:now};}):[];
  const store_analytics_events=options.includeOperationalData?rows(data,"store_analytics_events").map(row=>{const sourceOrderId=optionalUuid(row.order_id,"store_analytics_events.order_id"),sourceProductId=optionalUuid(row.product_id,"store_analytics_events.product_id"),mappedOrderId=sourceOrderId?orderMap.get(sourceOrderId)??null:null,mappedProductId=sourceProductId?productMap.get(sourceProductId)??null:null,sourceOrderNumber=nullableText(row.order_number);return{id:makeId(),store_id:context.target.id,customer_id:null,order_id:mappedOrderId,product_id:mappedProductId,visitor_id:nullableText(row.visitor_id),session_id:nullableText(row.session_id),event_name:requiredText(row.event_name,"store_analytics_events.event_name"),event_category:text(row.event_category,"engagement"),page_path:nullableText(row.page_path),page_type:nullableText(row.page_type),referrer:nullableText(row.referrer),traffic_source:nullableText(row.traffic_source),traffic_medium:nullableText(row.traffic_medium),traffic_campaign:nullableText(row.traffic_campaign),traffic_term:nullableText(row.traffic_term),traffic_content:nullableText(row.traffic_content),search_query:nullableText(row.search_query),order_number:mappedOrderId&&sourceOrderNumber?orderNumberMap.get(sourceOrderNumber)??null:sourceOrderNumber,quantity:row.quantity==null?null:int(row.quantity),value:row.value==null?null:int(row.value),currency_code:text(row.currency_code,"BDT"),metadata:replaceMappedIds(replaceUrls(jsonValue(row.metadata,{}),mediaByUrl),sharedMaps),user_agent:nullableText(row.user_agent),event_timestamp:nullableText(row.event_timestamp)??now,created_at:nullableText(row.created_at)??now};}):[];
  const store_pages=pageRows.map((row,index)=>({id:pageMap.get(sourceUuid(row,"id",`store_pages[${index}]`))!,store_id:context.target.id,slug:requiredText(row.slug,`store_pages[${index}].slug`),title:requiredText(row.title,`store_pages[${index}].title`),seo_title:nullableText(row.seo_title),seo_description:nullableText(row.seo_description),is_homepage:bool(row.is_homepage)&&(options.replaceTargetContent||!context.targetHasHomepage),created_at:now,updated_at:now}));
  const store_page_blocks=rows(data,"store_page_blocks").map((row,index)=>({id:makeId(),page_id:requireMapped(pageMap,row.page_id,`store_page_blocks[${index}].page_id`),store_id:context.target.id,block_type:requiredText(row.block_type,`store_page_blocks[${index}].block_type`),props:replaceMappedIds(replaceUrls(jsonValue(row.props,{}),mediaByUrl),sharedMaps),sort_order:int(row.sort_order),is_visible:bool(row.is_visible,true),created_at:now,updated_at:now,entrance_animation:nullableText(row.entrance_animation),hover_effect:nullableText(row.hover_effect),effect_override:row.effect_override==null?null:bool(row.effect_override),layout_variant:nullableText(row.layout_variant),custom_html:nullableText(row.custom_html),custom_css:nullableText(row.custom_css),responsive_config:jsonValue(row.responsive_config,{hiddenOn:[]})}));
  const store_page_revisions=rows(data,"store_page_revisions").map((row,index)=>({id:makeId(),page_id:requireMapped(pageMap,row.page_id,`store_page_revisions[${index}].page_id`),store_id:context.target.id,blocks_snapshot:replaceMappedIds(replaceUrls(jsonValue(row.blocks_snapshot,[]),mediaByUrl),sharedMaps),revision_label:text(row.revision_label,"Imported revision").slice(0,160),changed_by:null,created_at:now}));
  const site_settings=rows(data,"site_settings").map((row,index)=>({id:makeId(),key:requiredText(row.key,`site_settings[${index}].key`),value:rewriteSettingValue(requiredText(row.key,`site_settings[${index}].key`),row.value,mediaByUrl,sharedMaps),updated_at:now,updated_by:null,store_id:context.target.id}));
  const store_staff_invites=options.accessImportMode==="none"?[]:rows(data,"store_staff_invites").map((row,index)=>({id:makeId(),store_id:context.target.id,invite_code:`RESTORE-${operationToken}-${String(index+1).padStart(4,"0")}-${makeId().slice(0,8).toUpperCase()}`,email:nullableText(row.email),role:roleValue(row.role)==="owner"?"admin":roleValue(row.role),status:"pending",claimed_by:null,claimed_at:null,expires_at:null,metadata:jsonValue(row.metadata,{}),created_by:null,created_at:now,updated_at:now}));
  const store_memberships=options.accessImportMode!=="memberships_and_invites"?[]:rows(data,"store_memberships").flatMap((row,index)=>{const userId=sourceUuid(row,"user_id",`store_memberships[${index}]`);if(!context.authUserIds.has(userId))throw new Error(`store_memberships[${index}].user_id does not exist on the destination platform.`);if(userId===context.actorId&&!context.actorExistingRole)return[];let role=roleValue(row.role);if(userId===context.target.owner_id)role="owner";else if(role==="owner")role="admin";if(userId===context.actorId)role=atLeastRole(role,context.actorExistingRole);return[{id:makeId(),store_id:context.target.id,user_id:userId,role,invited_by:null,created_at:now,updated_at:now}];});
  const store_subscriptions=options.replaceSubscription?rows(data,"store_subscriptions").slice(0,1).map((row,index)=>({id:context.existingSubscription?.id||makeId(),store_id:context.target.id,plan_id:requiredText(row.plan_id,`store_subscriptions[${index}].plan_id`),status:["trialing","active","past_due","cancelled"].includes(text(row.status))?text(row.status):"trialing",trial_ends_at:nullableText(row.trial_ends_at),current_period_ends_at:nullableText(row.current_period_ends_at),provider:context.existingSubscription?.provider??null,provider_subscription_id:context.existingSubscription?.provider_subscription_id??null,created_at:now,updated_at:now})):[];
  const store={id:context.target.id,slug:options.preserveTargetSlug?context.target.slug:requiredText(sourceStore.slug,"store.slug"),custom_domain:context.target.custom_domain,description:nullableText(sourceStore.description),currency_code:text(sourceStore.currency_code,context.target.currency_code??"BDT"),locale:text(sourceStore.locale,context.target.locale??"en"),plan:store_subscriptions[0]?.plan_id??context.target.plan,store_type:text(sourceStore.store_type,context.target.store_type??"general"),logo_url:nullableText(replaceUrls(sourceStore.logo_url,mediaByUrl)),is_published:options.keepImportedStoreDraft?false:bool(sourceStore.is_published)};
  return{store,store_business_profiles,store_themes,product_categories,product_types,products,coupon_codes,blog_posts,orders:ordersPlan,product_reviews,contact_messages,customer_addresses,store_customer_profiles,store_analytics_events,store_pages,store_page_blocks,store_page_revisions,site_settings,store_staff_invites,store_memberships,store_subscriptions};
}
