import { storeSchema, type Store } from "@/lib/cms/schema";

export const DEFAULT_STORE_ID = "00000000-0000-4000-8000-000000000001";
export const DEFAULT_STORE_DESCRIPTION = "A demo storefront generated by Commerce Engine. Pay with bKash, Nagad, or COD.";
export const DEFAULT_STORE_CURRENCY_CODE = "BDT";
export const DEFAULT_STORE_LOCALE = "en-BD";

const defaultStoreData = {
  id: DEFAULT_STORE_ID,
  name: "Demo Store",
  slug: "threadbd",
  description: DEFAULT_STORE_DESCRIPTION,
  currencyCode: DEFAULT_STORE_CURRENCY_CODE,
  locale: DEFAULT_STORE_LOCALE,
  isPublished: true,
  theme: {
    presetId: "default",
    mode: "dark",
    headingFont: "'Outfit', sans-serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "0.5rem",
    customCssVars: {},
  },
  pages: [
    {
      id: "page-home",
      slug: "/",
      title: "Home",
      seoTitle: "Commerce Engine Demo Store",
      seoDescription: "Browse a demo storefront powered by Commerce Engine.",
      isHomepage: true,
      blocks: [
        {
          id: "block-countdown",
          type: "countdown",
          sortOrder: 0,
          isVisible: true,
          props: {},
        },
        {
          id: "block-hero",
          type: "hero",
          sortOrder: 1,
          isVisible: true,
          props: {},
        },
        {
          id: "block-categories",
          type: "category-showcase",
          sortOrder: 2,
          isVisible: true,
          props: {},
        },
        {
          id: "block-featured",
          type: "featured-products",
          sortOrder: 3,
          isVisible: true,
          props: {
            limit: 6,
          },
        },
        {
          id: "block-promo",
          type: "promo-banner",
          sortOrder: 4,
          isVisible: true,
          props: {},
        },
        {
          id: "block-social-feed",
          type: "social-feed",
          sortOrder: 5,
          isVisible: true,
          props: {
            title: "Styled by our customers",
            subtitle: "Real-life looks, product details, and campaign moments.",
            images: [
              "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
              "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80",
              "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80",
              "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
            ],
          },
        },
        {
          id: "block-trust-badges",
          type: "trust-badges",
          sortOrder: 6,
          isVisible: true,
          props: {
            title: "Shop with confidence",
            badges: [
              { icon: "truck", label: "Fast Delivery", description: "Dhaka and nationwide courier support." },
              { icon: "payment", label: "bKash Accepted", description: "Mobile payments, cards, and COD options." },
              { icon: "returns", label: "Easy Returns", description: "Clear exchange support for eligible items." },
            ],
          },
        },
        {
          id: "block-testimonials",
          type: "testimonials",
          sortOrder: 7,
          isVisible: true,
          props: {
            title: "Loved by first-time buyers",
            subtitle: "Social proof that makes new customers feel safer at checkout.",
            reviews: [
              { name: "Nusrat A.", rating: 5, comment: "The fabric felt premium and delivery inside Dhaka was very quick." },
              { name: "Rafi H.", rating: 5, comment: "Loved that I could pay with bKash and confirm sizing before ordering." },
              { name: "Sadia M.", rating: 4, comment: "Support replied fast and helped me exchange for the right fit." },
            ],
          },
        },
        {
          id: "block-trust-copy",
          type: "rich-text",
          sortOrder: 8,
          isVisible: true,
          props: {
            eyebrow: "Why shop with us",
            title: "Clear policies, familiar payments, and support after purchase",
            body: "Customers buy faster when the essentials are easy to trust.\n\n- bKash, Nagad, card, and cash on delivery options\n- Delivery expectations before checkout\n- Responsive support if an order needs attention",
            align: "center",
          },
        },
        {
          id: "block-faq",
          type: "faq-accordion",
          sortOrder: 9,
          isVisible: true,
          props: {
            title: "Questions before checkout",
            subtitle: "Answer the practical doubts that usually stop first-time buyers.",
            faqs: [
              { q: "How long does delivery take?", a: "Inside Dhaka orders usually arrive faster, while outside Dhaka deliveries may take a few extra days." },
              { q: "Which payment methods are available?", a: "Customers can usually pay with bKash, Nagad, cards, or cash on delivery depending on your setup." },
              { q: "Can I exchange an item?", a: "Eligible unworn items can be exchanged within the store's published exchange window." },
            ],
          },
        },
        {
          id: "block-recently-viewed",
          type: "recently-viewed",
          sortOrder: 10,
          isVisible: true,
          props: {},
        },
      ],
    },
    {
      id: "page-about",
      slug: "/about",
      title: "About",
      seoTitle: "About Demo Store",
      seoDescription: "Learn the story, values, and service promise behind the store.",
      isHomepage: false,
      blocks: [
        {
          id: "about-story",
          type: "rich-text",
          sortOrder: 0,
          isVisible: true,
          props: {
            eyebrow: "Our Story",
            title: "Tell customers where the brand comes from",
            body: "Use this page to explain your origin, the people behind the store, and why your products matter.\n\n- What you believe about product quality\n- How customers can get support\n- Why first-time buyers can trust you",
            align: "left",
          },
        },
        {
          id: "about-trust",
          type: "trust-badges",
          sortOrder: 1,
          isVisible: true,
          props: {
            title: "What customers can expect",
            badges: [
              { icon: "payment", label: "Familiar Payments", description: "bKash, Nagad, card, and COD support." },
              { icon: "support", label: "Responsive Support", description: "Help before and after checkout." },
              { icon: "shield", label: "Clear Policies", description: "Delivery and exchange expectations in plain language." },
            ],
          },
        },
      ],
    },
    {
      id: "page-policy",
      slug: "/policy",
      title: "Shipping & Policy",
      seoTitle: "Shipping & Policy",
      seoDescription: "Delivery, payment, exchange, and support information for customers.",
      isHomepage: false,
      blocks: [
        {
          id: "policy-summary",
          type: "rich-text",
          sortOrder: 0,
          isVisible: true,
          props: {
            eyebrow: "Store Policy",
            title: "Set clear expectations before purchase",
            body: "Summarize delivery times, return windows, payment terms, exchange rules, and support availability.",
            align: "left",
          },
        },
        {
          id: "policy-faq",
          type: "faq-accordion",
          sortOrder: 1,
          isVisible: true,
          props: {
            title: "Policy FAQs",
            subtitle: "Use these answers to reduce confusion before the customer orders.",
            faqs: [
              { q: "What is your exchange or return window?", a: "Explain how many days customers have, what condition the item must be in, and how they should request support." },
              { q: "How are delivery charges calculated?", a: "Clarify delivery charges by region and whether free delivery applies above a threshold." },
              { q: "How are order issues resolved?", a: "Explain what customers should do if an item is delayed, damaged, or incorrect." },
            ],
          },
        },
      ],
    },
  ],
} satisfies Store;

export const defaultStore = storeSchema.parse(defaultStoreData);
