import { storeSchema, type Store } from "@/lib/cms/schema";

const defaultStoreData = {
  id: "00000000-0000-4000-8000-000000000001",
  name: "Demo Store",
  slug: "threadbd",
  description: "A demo storefront generated by Commerce Engine. Pay with bKash, Nagad, or COD.",
  currencyCode: "BDT",
  locale: "en-BD",
  isPublished: true,
  theme: {
    presetId: "default",
    mode: "dark",
    headingFont: "'Outfit', sans-serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "0.5rem",
    customCssVars: {},
  },
  pages: [
    {
      id: "page-home",
      slug: "/",
      title: "Home",
      seoTitle: "Commerce Engine Demo Store",
      seoDescription: "Browse a demo storefront powered by Commerce Engine.",
      isHomepage: true,
      blocks: [
        {
          id: "block-countdown",
          type: "countdown",
          sortOrder: 0,
          isVisible: true,
          props: {},
        },
        {
          id: "block-hero",
          type: "hero",
          sortOrder: 1,
          isVisible: true,
          props: {},
        },
        {
          id: "block-promo",
          type: "promo-banner",
          sortOrder: 2,
          isVisible: true,
          props: {},
        },
        {
          id: "block-categories",
          type: "category-showcase",
          sortOrder: 3,
          isVisible: true,
          props: {},
        },
        {
          id: "block-featured",
          type: "featured-products",
          sortOrder: 4,
          isVisible: true,
          props: {
            limit: 6,
          },
        },
        {
          id: "block-recently-viewed",
          type: "recently-viewed",
          sortOrder: 5,
          isVisible: true,
          props: {},
        },
      ],
    },
  ],
} satisfies Store;

export const defaultStore = storeSchema.parse(defaultStoreData);
