import type { StorefrontOrderExperience } from "@/lib/cms/storefront-order-experience";
import type { StorefrontTemplateId } from "@/lib/cms/storefront-templates";

type OrderLabels = StorefrontOrderExperience["labels"];

type OrderLabelOverride =
  | Partial<OrderLabels>
  | ((context: { isDigitalCart: boolean; templateId: StorefrontTemplateId }) => Partial<OrderLabels>);

const registry: Partial<Record<StorefrontTemplateId, OrderLabelOverride>> = {
  food: {
    cartTitle: "Your Tray",
    cartEmptyTitle: "Your tray is empty",
    cartEmptyDescription: "Browse the menu and add dishes to start your order.",
    browseLabel: "Browse Menu",
    continueBrowsingLabel: "Continue browsing the menu",
    checkoutTitle: "Complete Your Order",
    detailsTitle: "Delivery Details",
    addressLabel: "Delivery Address",
    cityLabel: "Area / Zone",
    placeOrderLabel: "Place Food Order",
    orderPlacedDescription: "Your food order is in and the kitchen can prepare it next.",
    postOrderStatusLabel: "Estimated preparation and delivery",
    continueActionLabel: "Browse Menu",
    trackActionLabel: "Track Delivery",
    trackTitle: "Track Your Food Order",
    trackDescription: "Enter the order number and phone number used at checkout to see the latest preparation and delivery status.",
    optionLabel: "Portion",
    deliveryEstimateLabel: "30-60 minutes",
  },
  subscriptions: {
    detailsTitle: "Subscriber Details",
    addressLabel: "Account Email or Delivery Note",
    cityLabel: "Country / Region",
    placeOrderLabel: "Subscribe Now",
    orderPlacedTitle: "Subscription Request Confirmed",
    orderPlacedDescription: "Your subscription order has been placed and activation can begin after payment review.",
    postOrderStatusLabel: "Activation timing",
    continueActionLabel: "Browse Subscriptions",
    trackActionLabel: "Track Activation",
    trackTitle: "Track Your Subscription Order",
    trackDescription: "Enter the order number and phone number used at checkout to see the latest activation status.",
    optionLabel: "Plan",
    deliveryEstimateLabel: "Activation after confirmation",
  },
  "digital-downloads": {
    detailsTitle: "Customer Details",
    addressLabel: "Email or Delivery Note",
    cityLabel: "Country / Region",
    placeOrderLabel: "Purchase Download",
    orderPlacedTitle: "Download Order Confirmed",
    orderPlacedDescription: "Your digital order has been placed and download access can be prepared after payment confirmation.",
    postOrderStatusLabel: "Access timing",
    continueActionLabel: "Browse Downloads",
    trackActionLabel: "Track Access",
    trackTitle: "Track Your Download Order",
    trackDescription: "Enter the order number and phone number used at checkout to see the latest access and payment status.",
    optionLabel: "License",
    deliveryEstimateLabel: "Instant to short review time",
  },
  service: {
    cartTitle: "Service Request",
    cartEmptyTitle: "Your service request is empty",
    cartEmptyDescription: "Browse services and add the offers you want to request.",
    browseLabel: "Browse Services",
    continueBrowsingLabel: "Continue browsing services",
    checkoutTitle: "Service Request",
    detailsTitle: "Contact Details",
    addressLabel: "Address or Service Location",
    cityLabel: "City / Area",
    placeOrderLabel: "Request Service",
    orderPlacedTitle: "Service Request Confirmed",
    orderPlacedDescription: "Your request has been submitted and the team can follow up with the next steps.",
    postOrderStatusLabel: "Follow-up timing",
    continueActionLabel: "Browse Services",
    trackActionLabel: "Track Request",
    trackTitle: "Track Your Service Request",
    trackDescription: "Enter the request number and phone number used during checkout to see the latest status.",
    optionLabel: "Package",
    deliveryEstimateLabel: "Merchant follow-up",
  },
  booking: {
    cartTitle: "Booking Selection",
    cartEmptyTitle: "No bookings selected yet",
    cartEmptyDescription: "Browse availability and add the services or spaces you want to reserve.",
    browseLabel: "Browse Availability",
    continueBrowsingLabel: "Continue browsing availability",
    checkoutTitle: "Complete Your Booking",
    detailsTitle: "Booking Details",
    addressLabel: "Address or Special Request",
    cityLabel: "City / Area",
    placeOrderLabel: "Book Now",
    orderPlacedTitle: "Booking Request Confirmed",
    orderPlacedDescription: "Your booking request has been submitted and the team can confirm availability next.",
    postOrderStatusLabel: "Confirmation timing",
    continueActionLabel: "Browse Availability",
    trackActionLabel: "Track Booking",
    trackTitle: "Track Your Booking",
    trackDescription: "Enter the request number and phone number used during checkout to see the latest status.",
    optionLabel: "Booking option",
    deliveryEstimateLabel: "Availability confirmation",
  },
  hotel: {
    cartTitle: "Stay Selection",
    cartEmptyTitle: "No rooms selected yet",
    cartEmptyDescription: "Browse rooms and add the stay options you want to reserve.",
    browseLabel: "Browse Rooms",
    continueBrowsingLabel: "Continue browsing rooms",
    checkoutTitle: "Reserve Your Stay",
    detailsTitle: "Guest Details",
    addressLabel: "Address or Special Request",
    cityLabel: "City / Area",
    placeOrderLabel: "Reserve Stay",
    orderPlacedTitle: "Stay Request Confirmed",
    orderPlacedDescription: "Your stay request has been submitted and the property can confirm availability next.",
    postOrderStatusLabel: "Confirmation timing",
    continueActionLabel: "Browse Rooms",
    trackActionLabel: "Track Reservation",
    trackTitle: "Track Your Reservation",
    trackDescription: "Enter the request number and phone number used during checkout to see the latest status.",
    optionLabel: "Room option",
    deliveryEstimateLabel: "Availability confirmation",
  },
  "real-estate": {
    cartTitle: "Inquiry List",
    cartEmptyTitle: "Your inquiry list is empty",
    cartEmptyDescription: "Browse listings and save the properties you want to ask about.",
    browseLabel: "Browse Listings",
    continueBrowsingLabel: "Continue browsing listings",
    checkoutTitle: "Property Inquiry",
    detailsTitle: "Buyer / Renter Details",
    addressLabel: "Preferred Area or Address",
    cityLabel: "City / Location",
    placeOrderLabel: "Request Property Details",
    orderPlacedTitle: "Property Inquiry Confirmed",
    orderPlacedDescription: "Your property inquiry has been submitted and an agent can follow up next.",
    postOrderStatusLabel: "Agent follow-up timing",
    continueActionLabel: "Browse Listings",
    trackActionLabel: "Track Inquiry",
    trackTitle: "Track Your Property Inquiry",
    trackDescription: "Enter the inquiry number and phone number used during checkout to see the latest status.",
    optionLabel: "Listing option",
    deliveryEstimateLabel: "Agent follow-up",
  },
  "inquiry-catalog": {
    cartTitle: "Quote Request",
    cartEmptyTitle: "Your quote request is empty",
    cartEmptyDescription: "Browse products and add the items you want quoted.",
    browseLabel: "Browse Catalog",
    continueBrowsingLabel: "Continue browsing catalog",
    checkoutTitle: "Request a Quote",
    detailsTitle: "Business Contact Details",
    addressLabel: "Business Address",
    cityLabel: "City / Region",
    placeOrderLabel: "Submit Quote Request",
    orderPlacedTitle: "Quote Request Confirmed",
    orderPlacedDescription: "Your quote request has been submitted and the merchant can respond with pricing and next steps.",
    postOrderStatusLabel: "Merchant response timing",
    continueActionLabel: "Browse Catalog",
    trackActionLabel: "Track Request",
    trackTitle: "Track Your Quote Request",
    trackDescription: "Enter the request number and phone number used during checkout to see the latest status.",
    optionLabel: "Specification",
    deliveryEstimateLabel: "Merchant follow-up",
  },
  "single-product": {
    placeOrderLabel: "Complete Purchase",
    optionLabel: "Variant",
  },
};

export function getStorefrontOrderLabelOverride(
  templateId: StorefrontTemplateId,
  context: { isDigitalCart: boolean },
): Partial<OrderLabels> {
  const entry = registry[templateId];
  if (!entry) {
    return {};
  }

  return typeof entry === "function"
    ? entry({ ...context, templateId })
    : entry;
}
