-- Default plans and demo tenant seed.
-- Canonical source:
-- - 20260702000000_cms_engine_multi_tenant.sql

INSERT INTO public.cms_plans (id, name, description, monthly_price, store_limit, feature_flags, sort_order)
VALUES
  ('starter', 'Starter', 'Launch one store with core CMS blocks and manual payments.', 0, 1, '{"cms": true, "templates": true, "staff": 1}'::jsonb, 10),
  ('growth', 'Growth', 'Run campaigns, teams, coupons, reviews, and richer storefronts.', 1490, 3, '{"cms": true, "templates": true, "staff": 5, "analytics": true}'::jsonb, 20),
  ('scale', 'Scale', 'Agency and multi-brand package with custom domains and priority help.', NULL, NULL, '{"cms": true, "templates": true, "staff": -1, "custom_domains": true}'::jsonb, 30)
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  monthly_price = EXCLUDED.monthly_price,
  store_limit = EXCLUDED.store_limit,
  feature_flags = EXCLUDED.feature_flags,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

INSERT INTO public.stores (
  id,
  name,
  slug,
  description,
  currency_code,
  locale,
  plan,
  store_type,
  is_published
)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  'Demo Store',
  'threadbd',
  'A demo storefront generated by Commerce Engine.',
  'BDT',
  'en-BD',
  'starter',
  'clothing',
  true
)
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  updated_at = now();

INSERT INTO public.store_subscriptions (store_id, plan_id, status)
VALUES ('00000000-0000-4000-8000-000000000001', 'starter', 'active')
ON CONFLICT (store_id) DO UPDATE
SET plan_id = EXCLUDED.plan_id, status = EXCLUDED.status, updated_at = now();

INSERT INTO public.site_settings (store_id, key, value)
VALUES
  (
    '00000000-0000-4000-8000-000000000001',
    'brand_settings',
    '{"name": "Demo Store", "highlight": "", "seo_title": "Commerce Engine Demo Store", "seo_description": "Launch a mobile-first storefront with local payments and CMS-managed pages."}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000001',
    'contact_page',
    '{"address": "Dhaka, Bangladesh", "phone": "+880 1XXX-XXXXXX", "email": "hello@example.com"}'::jsonb
  )
ON CONFLICT (store_id, key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now();
